### PR TITLE
Add Advanced Search

### LINKED ISSUE #170: Display matched JSON lines in search result list
Something like this (when searching English, most importantly):
image

Book selection as shown in the image would not be essential for now. Just the part over the yellow background.

### PR DESCRIPTION
**Pull request by Reptilioo**
### Search
- Done through translations, comments, pali, titles, headings, pali titles.
- Works with or without diacritics regarding diacritics content.

### Search Options
- English, pali or both.
- Choose the books to search in.
- Exact Match: search a full word/expression and not part of it ("training" not "restraining").
- Single Result: displays one result max per sutta, the first one.

### Search Behaviors
- Shows up to 10 results for a given sutta.
- The search can be stopped at any moment using the "Stop" button.
- On screen higher than 767px: displays 150 words in english, 100 words in pali per result.
- On screen lower than 767px: displays 75 words in english, 100 words in pali per result.
- If match only with title/heading, displays first 150/100 words.
- Handles the use of ```'``` and ```’```, as well as ```...``` and ```…``` interchangeably.

### Search Style
- Added an "settings icon" in the right part of the search bar to access ```advanced-search.html```.
- The search panel is fixed and will follow the screen scrolling.
- On mobile the search panel is accessible using a dropdown button at the top of the page.
- Modified some margin/padding on the headers.

### Html highlight
- Added code to show or hide pali by fetching a ```pali``` parameter in the url.
- Added code to highlight the search term used by passing it in a ```search``` parameter in the url, highlights ```span.eng-lang``` si ```pali=="hide"```, highlights ```span.pli-lang``` si ```pali=="show"```.

### Database changes
- Modify the database from using only table ```suttas``` with translations, comments and pali, to two tables ```suttas_en``` (translation_en_anigha, comments) and  ```suttas_pl``` (root_pli_ms).
- Added code to handle the migration from the old database setup to the new one [though it will be useful only until the transition is complete for everyone, and could be removed later].
- Modified the databse update: So far the database update was only done when a new sutta was added, not when anything was modified within the existing ones. 
  Added a unique id/hash linked to the current ```python/generated/suttas-database-data.json``` that will be generated from ```python/scripts/suttas_database_data_generator.py```.
  The update-code will check if the hash is different from the one in the database and will update database and hash if that is the case.

### Misc
- Includes the changes made in #219: handles more different types of verseRanges with segment highlighting and scrolling to hash, when url is a link to a specific passage.

closes #170

### CODE REVIEW

**Comment by bkhpanigha** [comment]
@Reptilioo Great work. One tiny detail before we push it to live: can we enforce a search string minimum of 3 chars?

**Comment by Reptilioo** [comment]
> @Reptilioo Great work. One tiny detail before we push it to live: can we enforce a search string minimum of 3 chars?

We can but since the search isn't automatic I figured it wasn't necessary to put an arbitrary restriction. Should I add it anyway?

**Comment by Reptilioo** [comment]
Here is the full ```./js/utils/eventListeners/initializeSearchEvents.js``` to do so:

```
import { startSearch } from '../userActions/startSearch.js';
import { searchState } from '../userActions/searchState.js';

export function initializeSearchEvents() {
    document.querySelector('#searchButton').addEventListener('click', () => {
        if (searchState.isSearching) {
            searchState.shouldStopSearch = true;
        } else {
            startSearch();
        }
    });

    const searchInput = document.getElementById('searchInput');

    window.addEventListener("load", function() {
        const searchInput = document.getElementById("searchInput");
        const searchButton = document.getElementById("searchButton");
        const langInputs = Array.from(document.querySelectorAll('input[name="lang"]'));
        const categoryInputs = Array.from(document.querySelectorAll('input[name="book"]'));

        function checkInputs() {
            const searchValue = searchInput.value.trim();
            const isSearchInputValid = searchValue.length >= 3; // At least 3 characters
            const isLangChecked = langInputs.some(input => input.checked);
            const isCategoryChecked = categoryInputs.some(input => input.checked);
            
            searchButton.disabled = !(isSearchInputValid && isLangChecked && isCategoryChecked);
        }

        [...langInputs, ...categoryInputs].forEach(input => {
            input.addEventListener("change", checkInputs);
        });

        searchInput.addEventListener("input", checkInputs);
        checkInputs();

        document.addEventListener('keydown', function(event) {
            if (event.key === 'Enter') {
                if (!searchButton.disabled) {
                    startSearch();
                }
                event.preventDefault();
            }
        });
    });

    window.onload = () => searchInput.focus();
}
```

**Comment by bkhpanigha** [comment]
> > @Reptilioo Great work. One tiny detail before we push it to live: can we enforce a search string minimum of 3 chars?
> 
> @bkhpanigha We can, but since the search isn't automatically started I figured it wasn't necessary to put an arbitrary restriction. Should I add it anyway?

@Reptilioo I think that would then allow us to remove the results-per-sutta restriction (I haven't checked the code, but it seems like you implemented it as I suggested)

**Comment by Reptilioo** [comment]
@bkhpanigha Ok I get it, I will make a PR soon.

**Pull request merged**
