### PR TITLE
Add suttas content search

### PR DESCRIPTION
**Pull request by interested-in-dhamma**
### Done
**Core:**
- Add python script to store the suttas data that will be imported in the user's browser in IndexedDB --> using Dexie library.
- Add search bar that is capable of searching through sutta content
- Add reset button to footer where user can reset the website (resets the localStorage and IndexedDB, and reloads the page)

**Additional:**
- Move whatsNewArea to its own section.
    - Fix a bug where whatsNewArea is no longer shown after searching something and then clearing the search
- Add status to service worker logs

### Todo
- [x] Fix being able to search notes behind titles (this is happening because the citation + title is in the translation files, but not the notes behind a title)
- [x] Fix sorting of search results in new search

### Notes
- This new search overrides the old search. It requires some testing to see if something is missing.
- This feature is experimental, we have to check if it works well for every user performance wise. (Also to see if it works as expected for mobile devices.)

### CODE REVIEW

**Comment by bkhpanigha** [comment]
Two things I would consider essential before rolling it out:
(1) The ability to match with or without diacritics (e.g., find "jhāna" when typing "jhana")
(2) Searching Pāli _titles_ at the very least, since those are standard and more known, while the English titles vary across translations.

Also, how hard would it be to display the actual text (i.e. the whole JSON entry containing the search string) under each hit?

**Comment by bkhpanigha** [comment]
@interested-in-dhamma 
Two things I would consider essential before rolling it out:
(1) The ability to match with or without diacritics (e.g., find "jhāna" when typing "jhana")
(2) Searching Pāli _titles_ at the very least, since those are standard and more known, while the English titles vary across translations.

Also, how hard would it be to display the actual text (i.e. the whole JSON entry containing the search string) under each hit?

**Comment by interested-in-dhamma** [comment]
The 2 points have been addressed. The pali is now completely searchable as well. (Including the title).

I will get back to your point about displaying of the text.

**Comment by Reptilioo** [comment]
This is not extremely important for now but if I understand correctly: the database is only updated when new suttas are added and not when modifications are made in the already existing ones, right?

**Comment by interested-in-dhamma** [comment]
Yes that is right, I did not consider that during the implementation @Reptilioo

**Pull request merged**
