### PR TITLE
Youtube Preview Improvements

### PR DESCRIPTION
**Pull request by Reptilioo**
- More responsive
- Cleaner animations
- Less likely to stay stuck displayed, on desktop
- Preload data so they are not fetched every display
- Prettier preview offline

### CODE REVIEW

**Comment by Reptilioo** [comment]
I found that there was still a way to get the preview stuck on screen, so I made the adjustments so it hopefully never happens, but in the unlikely events that it does, I also added a way to make it disappear by clicking outside of it.
Now, I got to work on that restlessness.

**Comment by Reptilioo** [comment]
Preload thumbnails and other data only on desktop because it's most likely not on a limited data.

On mobile, wait for the user to interact with the link to download thumbnail and load data for the specific link. Data is then saved in a variable to not redownload everything if clicking the same link again.

**Comment by interested-in-dhamma** [comment]
@Reptilioo No thumbnail is shown for playlists. Maybe it is intentional but just to let you know. For example https://suttas.hillsidehermitage.org/?q=dn2#comment5

Maybe show something to distinguish that it is a playlist?

**Comment by Reptilioo** [comment]
Yes, I didn't bother taking into account the playlists, but if it is deemed necessary I'm open to suggestions

**Comment by interested-in-dhamma** [comment]
> @interested-in-dhamma Yes, I didn't bother taking into account the playlists, but if it is deemed necessary I'm open to suggestions, maybe just adding "Playlist: [Name of playlist]" next to the youtube button would do the job? I'm not even yet sure I can fetch playlist' data

Sounds good to me.

**Comment by Reptilioo** [comment]
Sure, I now know how I will do it, but I would rather do it later as an improvement of this version.

**Pull request merged**
