### PR TITLE
Basic comments

### PR DESCRIPTION
**Pull request by ishaanv**
#24 First version of comments. 

@bkhpanigha if you would like to include clickable links from these comments let me know as we will have to take a different approach.

### CODE REVIEW

**Comment by bkhpanigha** [comment]
I would actually like to have clickable links. I will most likely  be cross-referencing Suttas often. Coupled with the highlighting feature, having clickable links in the comments would be great.

**Comment by bkhpanigha** [comment]
It would also be ideal if the comments support basic markdown

**Comment by ishaanv** [comment]
Got it. @bkhpanigha Will you be able to write markdown and view it within your translation software?

**Comment by bkhpanigha** [comment]
> Got it. @bkhpanigha Will you be able to write markdown and view it within your translation software?

Yes, I'm already writing in markdown, including links.

**Comment by ishaanv** [comment]
@bkhpanigha this should now render markdown. Would be if you can test this against a sample comment file with markdown (or upload on here so I can test).

**Comment by bkhpanigha** [comment]
> @bkhpanigha this should now render markdown. Would be good if you can test this against a sample comment file with markdown (or upload on here so I can test.

Works great, thank you.

**Pull request merged**
