### PR TITLE
EPUB version

### LINKED ISSUE #161: Feature: Generate and download the ressource in .epub
Looks like some people with limited internet access could benefit from being able to download the entirety of the translations and comments in a .epub document.
Maybe we could generate a new epub document after every updates or once a month or something, not sure how process intensive it could be.
Not sure how to exactly do that yet.

Notes:
- the homepage would serve as the summary
- would need a note stating this isn't a definitive edition and mentionning the update frequence.

With calibre:
- Need to generate an index with every links to the suttas
- Need to generate special html pages containing only the content that will be displayed
- Need to put all that in a folder and use calibre to convert the whole thing into an epub

Need to look if there is a easier or more automated way to do this

### PR DESCRIPTION
**Pull request by Reptilioo**
Python script generating files to submit to Calibre in order to get an epub version of the english translations + comments

Generate:
-- every suttas as .xhtml files in "/suttas_epub/xhtml"
-- /suttas_epub/xhtml/nav.xhtml - the file to submit to calibre

- [x] Search how to get back to a passage from a footnote (instead of opening a popup showing the passage)
- [x] Add the html/css/js to download the epub file (display when the file was last uploaded?)
- [x] Having a table of content with the same informations than the website homepage
- [x] Sorting the table of content and adding Nikayas' names like the website homepage
- [x] Fix a bug duplicating files when importing
- [x] Check how to add Nikayas names in ToC (create an html page with only the Nikaya's name for content and add link to it?)
- [x] Check possible compatibility issues
- [x] Check for new bugs
- [x] Change cover
- [x] Fix conflicts and re-add the files

Later Improvements:
-- Any way to link to and highlight passages with EPUB?

closes #161

### CODE REVIEW

**Comment by Reptilioo** [comment]
Let me know if you want to modify some elements.

**Comment by Reptilioo** [comment]
I realized I had modified an old "index.js".

Let me know if you want to change elements.

**Comment by Reptilioo** [comment]
Corrected a bug

**Comment by Reptilioo** [comment]
Fixed a bug and simplified the code.

Now it's ready to roll, unless there are some changes to make

**Comment by bkhpanigha** [comment]
Nice work. A few suggestions before we roll it out: 

- Change the cover title to "Sutta Translations".
- Incorporate the divisions by Nikāya into the table of contents that's usually shown on EPUB reader apps (see image below). At minimum, it would be good to at least have the table of contents (which does have the divisions) as the first heading instead of the first DN Sutta.
- Display words wrapped in asterisks (generally found within comments) in italics.
- Can search be made to work with comments too? Right now, when you search for a string within a comment, the matches are displayed. But when you click on them nothing happens.

**Comment by Reptilioo** [comment]
Would you be able to tell me what you searched?
Also what EPUB reader did you use?

**Comment by bkhpanigha** [comment]
> @bkhpanigha Would you be able to tell me what you searched? Also what EPUB reader did you use?

@Reptilioo Ah, never mind. It seems it's my EPUB reader's fault (Foliate).

**Comment by Reptilioo** [comment]
> @Reptilioo Ah, never mind. It seems the comment search issue was my EPUB reader's fault (Foliate).

@bkhpanigha Ok, I will still look if this is a compatibility issue that can be quickly fixed before rollout, the goal is to make it wildly compatible.

**Comment by Reptilioo** [comment]
@bkhpanigha I tested with a different epub reader that wasn't able to find the text in comments, and I made some changes regarding them to fix it, I would like to test if it fixed the issue on Foliate too but I will only be able to install linux near the end of the week.
When you have some time could you quickly test a search on comments' content?

**Comment by bkhpanigha** [comment]
> @bkhpanigha I tested with a different epub reader that wasn't able to find the text in comments, and I made some changes regarding them to fix it, I would like to test if it fixed the issue on Foliate too but I will only be able to install linux near the end of the week. When you have some time could you quickly test a search on comments' content?

@Reptilioo Still having the same issue. Text is found but not displayed once clicked.

image

**Comment by Reptilioo** [comment]
@bkhpanigha If there are no other modifications to be made, this version is ready to roll.

To be honest, I'm not sure downloading the file will work first try, nor fetching the last modified date of the file to display it next to the download button but it did when I tested it.

Right now, we are going to have two buttons layered one above the other at the top right portion of the home page, but it should be modified with either #131, #141 or #173.

**Comment by bkhpanigha** [comment]
@Reptilioo 

> nor fetching the last modified date of the file to display it next to the download button but it did when I tested it.
Yes, that doesn't seem to work. I tried deleting everything except a few Suttas, and it still gives the EPUB with all the deleted files. Also tried adding a new Sutta, and it didn't get included in the EPUB.

**Comment by Reptilioo** [comment]
@bkhpanigha My bad I was probably unclear, it seems that you are talking about automatically modifying the .epub file when changes are made to the repository, am I right? For that I still didn't find a way to automate everything, I will still have to follow the process described in the "/suttas_epub/Calibre_Instructions.exe" to create a new ebook with the most recent changes, lets say every couple of weeks, or every month.

The line you quoted referred only to the "Last Updated" field when clicking in the info button (next to the "Get Ebook" button), which is supposed to display the date of the last update of the file so people can know if a more recent version is out.

**Pull request merged**
