### PR TITLE
Advanced search modifications

### PR DESCRIPTION
**Pull request by Reptilioo**
- Added 3 chars minimum in seach bar for search button to be enabled.
- Removed the limitations to 10 results maximum (and its reference in the html).
- Improved the results display so if a result is ready to show it is instantly displayed instead of waiting for the whole sutta to be processed.
- Improved the loading bar behavior.

### CODE REVIEW

**Comment by bkhpanigha** [comment]
@Reptilioo Great, now it's live. You can announce the new feature on the subreddit if you want

**Comment by bkhpanigha** [comment]
@Reptilioo Actually, one thing I just noticed is that due to the new range separator "_", links in comments no longer work properly. I could easily fix that with some regex, but I can't do that with Reddit posts that have such links.

**Comment by Reptilioo** [comment]
@bkhpanigha Ah, you're right. I'm thinking about it, It gave me a hard time with the "-" being either between verses, or between chapters like an1.51-60 or between verses like mn28:29-30.1. 
Maybe we can create a redirection from the "-" to the "_" format for such links?

**Comment by bkhpanigha** [comment]
> @bkhpanigha Ah, you're right. I'm thinking about it, It gave me a hard time with the "-" being either between verses like mn1-mn2, or between chapters like an1.51-60 or between verses like mn28:29-30.1. 
> Maybe we can create a redirection from the "-" to the "_" format for such links?

@Reptilioo Sure, that would work.

**Pull request merged**
