### PR TITLE
Add Youtube link preview

### LINKED ISSUE #191: Feature: display video infos when hovering link
We could have a small box showing video thumbnail, title, duration, even part of the description when hovering over a youtube link in the comments

### PR DESCRIPTION
**Pull request by Reptilioo**
Add Youtube link preview when hovering a link:
- Light theme/dark theme
- No use on mobile so doesn't load on mobile

Let me know if something should change.

closes #191

### CODE REVIEW

**Comment by bkhpanigha** [comment]
Very good. Why not on mobile? Because it's too difficult/impractical? If so then it's fine, but if it's possible then I think it'd be worth adding, even if it requires the user to tap on the link twice to go to the video. In fact, I bet most people who use the app offline will be doing so on mobile. 

The problem perhaps is that the thumbnails would have to be added to` files_to_cache.json` for the feature to work offline?

**Comment by Reptilioo** [comment]
@bkhpanigha I disabled it on mobile because they can't hover a cursor over a link, but yes, we can surely add a different two-taps approach for mobile. Maybe even make these links stand out compared to the other links with a youtube or play icon next to the text url.

I never thought that some people could have lots of HH videos downloaded on their phones, but an offline behavior can be imagined too, we would need to get all HH videos id (the part at the end of the video's link) as well as the titles —I'm open to hear what could be an easy way to do so— and put them in a file to cache.

**Comment by Reptilioo** [comment]
@bkhpanigha Yes I didn't think about the need to do it automatically for the updates, I found a way to do it with a python module but it needed multiples dependencies, I will check if there is a relatively lightweight python module to extract data from youtube without a paid youtube api key needed.

**Comment by Reptilioo** [comment]
@bkhpanigha I set up a new ```.yml``` file for scheduled task (set to run sunday at midnight) with which a python script runs and fetch videos data (titles, thumbnails links, video duration) from @HillsideHermitage and @SamanadipaHermitage and puts them into a ```.json```, in the same way we do with ```available_suttas.json```.
The code in ```YoutubePreview.js``` no longer fetch data by making requests to youtube, but instead get the data from this json.

Change the way to hide preview on mobile, from clicking on an arrow icon to clicking outside the preview.

When offline, it displays everything except the thumbnail.

**Pull request merged**
