### PR TITLE
Adv. search style modifications

### PR DESCRIPTION
**Pull request by Reptilioo**
#### - Added a left-border specific color to differentiate english, pali and comment content, as well as a label in the top right corner of the result

_Contains modifications from #243_

<hr>

Feel free to let me know if this is too much, distracting or distasteful.

Also, would you mind if we had multiple polished site-wide themes to choose from in a setting menu?

### CODE REVIEW

**Comment by Reptilioo** [comment]
Also modified highlighting color of the search terms on the sutta page to match highlighting in search results.

**Comment by bkhpanigha** [comment]
@Reptilioo Before testing this, I was just about to suggest that we should distinguish the different types of results in some obvious way, and this works great.

>Also, would you mind if we had multiple polished site-wide themes to choose from in a setting menu?

Could do, although it would be a low-on-the-priority list feature. Getting the settings menu itself (which could also contain things like Dark Mode, Use Offline, and Ebook download, and Reset Website) would probably be more important.

**Comment by bkhpanigha** [comment]
@Reptilioo Also, there are merge conflicts on this PR that are not immediately obvious to resolve. Could you take a look at them and submit a new PR once resolved?

**Comment by Reptilioo** [comment]
@bkhpanigha That is the first time I'm resolving conflicts, I corrected them all before I realised that there were really no reason to have conflicts since the HTML and CSS I'm PRing are the final version anyway, there was still a small difference of 7 lines corresponding to one css element, so I ended up just overwriting the code. Do you know if it can cause issues down the line?

When you say "submit a new PR", do you mean litterally opening a new Pull Requests?

**Comment by bkhpanigha** [comment]
> When you say "submit a new PR", do you mean litterally opening a new Pull Request?

@Reptilioo Never mind. I wasn't sure if you'd be able to fix the conflicts from your side, but you were.

> there was still a small difference of 7 lines corresponding to one css element, so I ended up just overwriting the code. Do you know if it can cause issues down the line on github side?

I don't think so. The issue would be for us if we end up pushing code that we didn't actually intend to use.

**Comment by Reptilioo** [comment]
@bkhpanigha This is just an idea and I might come up with something better, but would you be open to redesigning the header?

I'm thinking that implementing a basic navigation-bar in the same style as suttacentral one could be cleaner. The navbar would work as a header and follow the window when scrolling by staying at the top of screen.

_Subnavigation menu_: What we have on [hillsidehermitage.org](https://www.hillsidehermitage.org/) for the "Teachings button".

We could have:
- A home button as an house icon, as it already is.
- A subnavigation menu with "Content" as a button, and with "Bookmarks", "Comments", "Glossary" as subnav buttons.
- A subnavigation menu with "Links" as a button, and the current 3 top left links as subnav buttons.
- A subnavigatio menu with "Download" as a button, and the current 2 top right buttons as subnav buttons.
- An "[About page](https://github.com/bkhpanigha/hh-suttas/issues/141)".
- A "[Setting panel](https://github.com/bkhpanigha/hh-suttas/pull/173)" that is opened by clicking a cog. 

The setting panel would have:
- Toggle pali
- Toggle dark mode
- Increase/decrease font-size
- Reset website

On mobile this menu should be more ergonomic and accessible than the Suttacentral one, with a [3 horizontal bars](https://iconmonstr.com/line-three-horizontal-lined-svg/) icon to open the previously described menu but in a style made to fit a mobile.

**Pull request merged**
