### PR TITLE
bookmarks first version

### LINKED ISSUE #25: Bookmark functionality
Would it be useful to be able to save and group snippets from different suttas?

### PR DESCRIPTION
**Pull request by ishaanv**
Closes #25 
First version. Need to fix the file path issue for books that aren't DN and MN (see #77).

TODO for this version:
- [X] Fix path so it works for all books
- [ ] ~Fix display and formatting e.g. icons for delete~ leaving this for later
- [X] Upload/Download as json (nice to have: google drive sync)
- [X] ~toggle all functionality (nice to have)~ toggle state is saved now
- [X] tests

@bkhpanigha @Reptilioo would be interested in your feedback if this is actually useful or not.
image

image

### CODE REVIEW

**Comment by Reptilioo** [comment]
Good work already 👍 

I tested it a bit locally and I can make one bookmark, then I go to delete it and then I'm not able to create new bookmarks after that with error:
``bookmarks.unlabeled is undefined
  clickHandler http://localhost/js/utils.js:139``

But that's great that we have a first draft and the structure, we can polish it from there 😄

**Comment by bkhpanigha** [comment]
@ishaanv  Good feature if it can be made to work reliably.

**Comment by ishaanv** [comment]
> Good work already 👍
> 
> I tested it a bit locally and I can make one bookmark, then I go to delete it and then I'm not able to create new bookmarks after that with error:
> 
> bookmarks.unlabeled is undefined
> 
> clickHandler http://localhost/js/utils.js:139
> Not sure if it comes from my setup.
> 
> But that's great that we have a first draft and the structure, we can polish it from there 😄

That's a bug, nice catch! Which reminds me that it should ship with tests.

On the topic of reliability, since there is state management involved in this feature, it's much harder to recover from mistakes or ship updates. So I'll restructure the available_suttas.json first so this can reliably work for all books. Meanwhile if you find any further bugs, do let me know.

**Comment by ishaanv** [comment]
I was unable to create tests that actually select text from a sutta and then bookmark it. But I have other tests that test the upload download functionality as consolation. I think it's good enough to be used and improved on later. But would be great to have one final test round @bkhpanigha

**Pull request closed without merging**
